### ISSUE TITLE
About Pagefind Style

### ISSUE THREAD

**Issue by EveSunMaple** [isooosi/astroverse#113]
### 错误样式

搜索页面结果与页脚相互叠加：

![QQ_1725546041560](https://github.com/user-attachments/assets/6786b78a-b919-43a7-959d-df4f95ceb070)

![QQ_1725546162211](https://github.com/user-attachments/assets/969f4b1a-398a-4a92-8adf-05c7159c4e4d)

### 问题复现

在主题搜索页面输入 "k"

**Comment by isooosi** [comment]
fix(layout): Ensure footer stays at the bottom of the page and content auto-fills height

- Applied flexbox layout in BaseLayout.astro to keep the footer at the bottom of the page.
- Used `flex-grow` for the main content area to dynamically adjust height based on the content.
- Added `pb-32` to ensure proper spacing between the content and footer in search.astro.
- Limited the Pagefind search box height and ensured it fits various screen sizes.
see more [ea12b32](https://github.com/isooosi/astroverse/commit/ea12b329118c0bf9e121116616f00df45f509287)
